### ISSUE TITLE
installing module

### ISSUE THREAD

**Issue by lagrz** [jacobb/prowlpy#2]
hey guys i keep getting this when i try installing the module

Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    from prowlpy import **author** 
  File "python/prowlpy.py", line 13, in <module>
    from httplib2 import Http
  File "/Library/Python/2.6/site-packages/httplib2/**init**.py", line 38, in <module>
    import http.client
ImportError: No module named http.client

would you mind helping me out? I'm running the python version that comes standard with OSX Snow Leopard

**Comment by ohe** [comment]
Hummph... The second error is tricky. http.client is a module of python3..
What's the version of httplib2 have you installed?

**Comment by lagrz** [comment]
okay i resolved this by installing pythong 2.6.4 i just didnt realize that by default it didnt update the shell command on OSX i guess i just have to use python2.6 setup.py install thanks though :D

**Comment by ohe** [comment]
Okay, i think that jacobb can close this issue now.

**Comment by ohe** [comment]
Closing this issue
